export type City = {
  slug: string;
  name: string;
  dept: string;
  deptNum: string;
  region: string;
  cpam: string;
  intro: string;
  nbCds: string;
};

export const cities: City[] = [
  {
    slug: "paris",
    name: "Paris",
    dept: "Paris",
    deptNum: "75",
    region: "Île-de-France",
    cpam: "CPAM de Paris",
    intro: "Paris concentre la plus forte densité de centres de santé en France, avec une majorité de CDS associatifs, mutualistes et municipaux. La CPAM de Paris traite chaque année plusieurs centaines de dossiers Teulade, avec des délais souvent allongés.",
    nbCds: "plus de 90",
  },
  {
    slug: "marseille",
    name: "Marseille",
    dept: "Bouches-du-Rhône",
    deptNum: "13",
    region: "Provence-Alpes-Côte d’Azur",
    cpam: "CPAM des Bouches-du-Rhône",
    intro: "Deuxième ville de France, Marseille compte un tissu dense de centres de santé associatifs et municipaux, particulièrement dans les quartiers nord. La CPAM des Bouches-du-Rhône instruit les dossiers Teulade pour l’ensemble du département.",
    nbCds: "plus de 35",
  },
  {
    slug: "lyon",
    name: "Lyon",
    dept: "Rhône",
    deptNum: "69",
    region: "Auvergne-Rhône-Alpes",
    cpam: "CPAM du Rhône",
    intro: "Lyon et la métropole lyonnaise comptent un nombre croissant de centres de santé pluriprofessionnels, portés par des associations et collectivités. La CPAM du Rhône applique strictement les modalités de l’article L162-32.",
    nbCds: "plus de 30",
  },
  {
    slug: "toulouse",
    name: "Toulouse",
    dept: "Haute-Garonne",
    deptNum: "31",
    region: "Occitanie",
    cpam: "CPAM de la Haute-Garonne",
    intro: "Toulouse dispose d’un maillage de centres de santé en développement rapide, notamment via les structures pluriprofessionnelles et les centres municipaux. La CPAM de Haute-Garonne instruit la subvention Teulade pour l’ensemble du département.",
    nbCds: "plus de 20",
  },
  {
    slug: "nice",
    name: "Nice",
    dept: "Alpes-Maritimes",
    deptNum: "06",
    region: "Provence-Alpes-Côte d’Azur",
    cpam: "CPAM des Alpes-Maritimes",
    intro: "La métropole niçoise et les communes alentours abritent plusieurs centres de santé dentaires et pluriprofessionnels. La CPAM des Alpes-Maritimes traite les dossiers Teulade pour les CDS du 06.",
    nbCds: "plus de 15",
  },
  {
    slug: "nantes",
    name: "Nantes",
    dept: "Loire-Atlantique",
    deptNum: "44",
    region: "Pays de la Loire",
    cpam: "CPAM de la Loire-Atlantique",
    intro: "Nantes et son agglomération ont vu un fort développement des centres de santé pluriprofessionnels associatifs. La CPAM de Loire-Atlantique applique la subvention Teulade dans les conditions standards.",
    nbCds: "plus de 18",
  },
  {
    slug: "montpellier",
    name: "Montpellier",
    dept: "Hérault",
    deptNum: "34",
    region: "Occitanie",
    cpam: "CPAM de l’Hérault",
    intro: "Montpellier connaît une dynamique forte de création de CDS, notamment polyvalents. La CPAM de l’Hérault instruit les dossiers Teulade des centres du département.",
    nbCds: "plus de 15",
  },
  {
    slug: "strasbourg",
    name: "Strasbourg",
    dept: "Bas-Rhin",
    deptNum: "67",
    region: "Grand Est",
    cpam: "CPAM du Bas-Rhin",
    intro: "Strasbourg dispose d’un maillage historique de centres mutualistes et municipaux. La CPAM du Bas-Rhin traite les dossiers Teulade pour l’ensemble de l’Alsace-nord.",
    nbCds: "plus de 12",
  },
  {
    slug: "bordeaux",
    name: "Bordeaux",
    dept: "Gironde",
    deptNum: "33",
    region: "Nouvelle-Aquitaine",
    cpam: "CPAM de la Gironde",
    intro: "Bordeaux et son agglomération ont vu de nombreuses ouvertures de CDS dentaires et médicaux ces dernières années. La CPAM de la Gironde reste l’interlocuteur unique pour la subvention Teulade.",
    nbCds: "plus de 14",
  },
  {
    slug: "lille",
    name: "Lille",
    dept: "Nord",
    deptNum: "59",
    region: "Hauts-de-France",
    cpam: "CPAM de Lille-Douai",
    intro: "La métropole européenne de Lille compte un réseau dense de centres associatifs et municipaux, particulièrement en lien avec les collectivités. La CPAM de Lille-Douai instruit les dossiers Teulade pour le secteur.",
    nbCds: "plus de 25",
  },
  {
    slug: "rennes",
    name: "Rennes",
    dept: "Ille-et-Vilaine",
    deptNum: "35",
    region: "Bretagne",
    cpam: "CPAM d’Ille-et-Vilaine",
    intro: "Rennes et la Bretagne sont particulièrement actives sur l’exercice coordonné. Plusieurs CDS pluriprofessionnels ont ouvert récemment. La CPAM d’Ille-et-Vilaine traite la subvention Teulade.",
    nbCds: "plus de 10",
  },
  {
    slug: "reims",
    name: "Reims",
    dept: "Marne",
    deptNum: "51",
    region: "Grand Est",
    cpam: "CPAM de la Marne",
    intro: "Reims et la Champagne disposent d’un tissu en construction de centres pluriprofessionnels. La CPAM de la Marne accompagne les CDS pour leur subvention Teulade.",
    nbCds: "plus de 8",
  },
  {
    slug: "saint-etienne",
    name: "Saint-Étienne",
    dept: "Loire",
    deptNum: "42",
    region: "Auvergne-Rhône-Alpes",
    cpam: "CPAM de la Loire",
    intro: "Saint-Étienne mise depuis plusieurs années sur les centres municipaux de santé pour répondre à la désertification médicale. La CPAM de la Loire instruit les dossiers Teulade pour l’ensemble du département.",
    nbCds: "plus de 10",
  },
  {
    slug: "le-havre",
    name: "Le Havre",
    dept: "Seine-Maritime",
    deptNum: "76",
    region: "Normandie",
    cpam: "CPAM de Rouen-Elbeuf-Dieppe & du Havre",
    intro: "Le Havre dispose de centres de santé municipaux et associatifs implantés depuis longtemps. La CPAM du Havre traite la subvention Teulade pour les CDS havrais.",
    nbCds: "plus de 6",
  },
  {
    slug: "grenoble",
    name: "Grenoble",
    dept: "Isère",
    deptNum: "38",
    region: "Auvergne-Rhône-Alpes",
    cpam: "CPAM de l’Isère",
    intro: "Grenoble compte plusieurs centres de santé associatifs et mutualistes. La CPAM de l’Isère est l’interlocuteur pour la subvention Teulade dans le département.",
    nbCds: "plus de 10",
  },
  {
    slug: "dijon",
    name: "Dijon",
    dept: "Côte-d’Or",
    deptNum: "21",
    region: "Bourgogne-Franche-Comté",
    cpam: "CPAM de la Côte-d’Or",
    intro: "Dijon et la Bourgogne voient se développer des centres pluriprofessionnels en zones rurales et péri-urbaines. La CPAM de la Côte-d’Or instruit la subvention Teulade.",
    nbCds: "plus de 7",
  },
  {
    slug: "angers",
    name: "Angers",
    dept: "Maine-et-Loire",
    deptNum: "49",
    region: "Pays de la Loire",
    cpam: "CPAM du Maine-et-Loire",
    intro: "Angers et son agglomération comptent un maillage croissant de centres pluriprofessionnels. La CPAM du Maine-et-Loire traite la subvention Teulade.",
    nbCds: "plus de 8",
  },
  {
    slug: "clermont-ferrand",
    name: "Clermont-Ferrand",
    dept: "Puy-de-Dôme",
    deptNum: "63",
    region: "Auvergne-Rhône-Alpes",
    cpam: "CPAM du Puy-de-Dôme",
    intro: "Le Puy-de-Dôme et l’Auvergne sont fortement engagés sur l’exercice coordonné. Plusieurs CDS municipaux et associatifs y opèrent. La CPAM du Puy-de-Dôme instruit la subvention Teulade.",
    nbCds: "plus de 7",
  },
  {
    slug: "tours",
    name: "Tours",
    dept: "Indre-et-Loire",
    deptNum: "37",
    region: "Centre-Val de Loire",
    cpam: "CPAM d’Indre-et-Loire",
    intro: "La région tourangelle développe son maillage de centres pluriprofessionnels notamment en lien avec les collectivités. La CPAM d’Indre-et-Loire traite la subvention Teulade.",
    nbCds: "plus de 6",
  },
  {
    slug: "amiens",
    name: "Amiens",
    dept: "Somme",
    deptNum: "80",
    region: "Hauts-de-France",
    cpam: "CPAM de la Somme",
    intro: "Amiens et la Picardie misent sur les centres de santé pour répondre à la sous-densité médicale. La CPAM de la Somme accompagne les CDS du département pour la subvention Teulade.",
    nbCds: "plus de 5",
  },
  {
    slug: "metz",
    name: "Metz",
    dept: "Moselle",
    deptNum: "57",
    region: "Grand Est",
    cpam: "CPAM de la Moselle",
    intro: "Metz et la Moselle développent leur offre de soins coordonnés. Plusieurs CDS municipaux et associatifs sont actifs. La CPAM de la Moselle instruit la subvention Teulade.",
    nbCds: "plus de 6",
  },
  {
    slug: "perpignan",
    name: "Perpignan",
    dept: "Pyrénées-Orientales",
    deptNum: "66",
    region: "Occitanie",
    cpam: "CPAM des Pyrénées-Orientales",
    intro: "Perpignan compte plusieurs centres de santé dentaires et médicaux. La CPAM des Pyrénées-Orientales est l’interlocuteur pour la subvention Teulade.",
    nbCds: "plus de 5",
  },
  {
    slug: "nimes",
    name: "Nîmes",
    dept: "Gard",
    deptNum: "30",
    region: "Occitanie",
    cpam: "CPAM du Gard",
    intro: "Nîmes et le Gard voient se créer plusieurs centres pluriprofessionnels. La CPAM du Gard instruit les dossiers Teulade des CDS du département.",
    nbCds: "plus de 5",
  },
  {
    slug: "limoges",
    name: "Limoges",
    dept: "Haute-Vienne",
    deptNum: "87",
    region: "Nouvelle-Aquitaine",
    cpam: "CPAM de la Haute-Vienne",
    intro: "Limoges et le Limousin sont particulièrement concernés par la désertification médicale et la création de CDS. La CPAM de la Haute-Vienne accompagne les centres pour la subvention Teulade.",
    nbCds: "plus de 4",
  },
];

export function getCity(slug: string) {
  return cities.find((c) => c.slug === slug);
}
