// Questions fréquentes de la page /faq.
//
// Sur la subvention Teulade : nommer le dispositif, jamais la méthode.

export const faqItems: { q: string; a: string }[] = [
  { q: "Qu’est-ce que la subvention Teulade ?", a: "Un dispositif spécifique aux centres de santé conventionnés, prévu par le code de la sécurité sociale. Il s’inscrit dans l’ensemble des financements publics et conventionnels mobilisables par un CDS. Il reste très peu connu des gestionnaires, y compris de ceux qui pilotent des structures installées depuis de longues années. Nous ne détaillons pas publiquement ses modalités : c’est le cœur de notre métier, et nous l’instruisons pour nos clients dans le cadre d’une mission. Contactez-nous pour un check-up." },
  { q: "Mon centre peut-il prétendre à la subvention Teulade ?", a: "Les centres de santé conventionnés peuvent en principe être concernés. Chaque situation s’apprécie individuellement, au regard de votre conventionnement, de votre organisation et de l’historique de votre structure. Nous vérifions ce point en amont, avant tout engagement de votre part, et nous vous le disons franchement si la piste ne tient pas. Contactez-nous pour un check-up gratuit." },
  { q: "Pourquoi cette subvention est-elle si peu demandée ?", a: "Parce qu’elle est ancienne, discrète et jamais mise en avant auprès des gestionnaires. Les équipes de direction sont absorbées par le quotidien, le recrutement médical et la trésorerie, et personne ne vient leur signaler ce qu’elles n’ont pas demandé. Les experts-comptables généralistes connaissent rarement les spécificités du secteur des centres de santé. Résultat : des structures parfaitement légitimes passent à côté, année après année, sans jamais en avoir eu connaissance. C’est précisément pour cette raison que notre cabinet existe." },
  { q: "Quels types de centres accompagnez-vous ?", a: "Centres médicaux, dentaires, infirmiers, polyvalents, pluriprofessionnels, qu’ils soient associatifs, mutualistes, municipaux ou en SCIC. Chaque famille a son économie propre : un centre dentaire ne se pilote pas comme un centre infirmier, et un centre municipal ne répond pas aux mêmes contraintes qu’une structure associative. Nous adaptons donc l’analyse au modèle réel de la structure, pas à un schéma théorique. Nous intervenons aussi bien sur des centres installés que sur des projets encore à l’état d’intention." },
  { q: "Sur quels sujets intervenez-vous ?", a: "Création, recrutement, organisation, gestion, financements, dossiers ARS, conformité. Notre offre phare reste la récupération des subventions. Nous intervenons également sur l’optimisation de l’activité, les achats et investissements, la comptabilité de gestion et la communication auprès de la patientèle. Selon les cas, la mission peut porter sur un point précis ou sur une remise à plat plus large du modèle économique." },
  { q: "Comment commence une mission ?", a: "Par un échange. Vous nous écrivez quelques lignes, on en discute, on définit ensemble s’il y a matière à travailler. Nous vous demandons ensuite un petit nombre de documents de cadrage pour objectiver la situation, plutôt qu’un dossier complet dès le départ. Si nous estimons qu’il n’y a rien à aller chercher, nous vous le disons et la discussion s’arrête là." },
  { q: "Êtes-vous indépendants ?", a: "Oui. Cabinet privé sans lien capitalistique avec la CPAM, l’URSSAF ou l’Assurance Maladie. Nous ne sommes pas non plus adossés à un groupe de santé, à un fournisseur d’équipements ou à un éditeur de logiciels, ce qui nous permet de vous conseiller sans conflit d’intérêts. Nos recommandations n’ont aucune raison de vous orienter vers un prestataire plutôt qu’un autre." },
  { q: "Travaillez-vous partout en France ?", a: "Oui, sur l’ensemble du territoire métropolitain et ultramarin. L’essentiel du travail se fait à distance, ce qui évite de facturer des déplacements inutiles et raccourcit les délais de traitement. Nous nous déplaçons lorsque le sujet le justifie vraiment, par exemple pour un audit d’organisation ou une réunion de gouvernance. Les spécificités régionales, notamment la relation avec l’ARS compétente, sont intégrées à l’analyse." },
  { q: "Quels sont les autres financements d’un centre de santé ?", a: "Au-delà de la subvention Teulade, plusieurs dispositifs publics et conventionnels peuvent être mobilisés. On y trouve notamment les financements prévus par l’accord national des centres de santé, les forfaits liés à la structure et à la coordination, les crédits du fonds d’intervention régional, ainsi que les aides des collectivités territoriales et les dispositifs propres aux zones sous-denses. Chaque dispositif a ses conditions et ne se cumule pas librement avec les autres. Notre check-up gratuit identifie les leviers adaptés à votre situation." },
  { q: "Pouvez-vous nous aider à recruter des médecins ?", a: "Oui. Nous orchestrons le recrutement de médecins salariés et mobilisons nos partenaires recruteurs spécialisés dans la santé pour le sourcing. Du cadrage du besoin à l’intégration du praticien, vous gardez un interlocuteur unique. Contactez-nous pour un check-up." },
  { q: "Comment êtes-vous rémunérés sur le recrutement de médecins ?", a: "Nous travaillons au résultat, sans vous engager sur des frais avant d’avoir avancé concrètement sur votre recrutement. Les conditions sont posées clairement dès le premier échange, sans frais cachés." },
  { q: "En quoi consiste concrètement le check-up ?", a: "C’est un premier examen de votre centre destiné à repérer ce qui est mobilisable et ce qui ne l’est pas. Nous regardons votre statut, votre conventionnement, votre activité, votre organisation et les financements déjà perçus, puis nous vous restituons une lecture claire de votre situation. L’objectif n’est pas de produire un rapport théorique mais de vous dire ce qui mérite d’être engagé, dans quel ordre et avec quel effort. Il est gratuit et sans engagement, et il aboutit parfois à la conclusion qu’il n’y a rien à faire de notre côté." },
  { q: "Comment êtes-vous rémunérés sur les missions de subventions ?", a: "Nous privilégions la rémunération au résultat : notre intérêt est aligné sur le vôtre, et vous ne payez pas pour une démarche qui n’aboutit pas. Les modalités sont écrites, discutées avant le lancement et ne comportent pas de frais cachés. Pour les missions de conseil plus classiques, organisation, création, pilotage, nous fonctionnons sur un cadre convenu à l’avance. Dans tous les cas, vous savez ce que vous engagez avant de nous confier quoi que ce soit." },
  { q: "Combien de temps notre équipe doit-elle y consacrer ?", a: "Le moins possible, c’est un principe de travail. Nous partons du postulat qu’une direction de centre de santé n’a pas de temps disponible et que le projet doit avancer sans mobiliser vos soignants. Concrètement, nous vous demandons des documents et quelques points de validation, et nous prenons en charge la préparation, la rédaction et le suivi. Un accompagnement qui vous coûte du temps de coordination plus qu’il ne vous en fait gagner n’a aucun intérêt." },
  { q: "Quelle différence entre un centre de santé et une maison de santé ?", a: "Le centre de santé est une structure d’exercice salarié, portée par un gestionnaire personne morale, qui pratique le tiers payant et relève de l’accord national des centres de santé. La maison de santé pluriprofessionnelle regroupe des professionnels libéraux qui coordonnent leur exercice tout en restant indépendants. Les conséquences sont lourdes : gouvernance, contrats de travail, responsabilité de l’employeur, modèle de financement et rapport à l’ARS n’ont rien à voir. Le choix entre les deux se fait au moment du projet, en fonction du territoire, des professionnels disponibles et du porteur." },
  { q: "Comment se déroule la création d’un centre de santé ?", a: "Elle commence par la définition du porteur et du besoin de santé du territoire, puis par la construction du projet de santé et du modèle économique. Viennent ensuite le choix du statut juridique du gestionnaire, les locaux, les équipements, le recrutement de l’équipe et la constitution du dossier déposé auprès de l’ARS. L’ouverture effective suppose enfin le conventionnement et la mise en place des outils de facturation et de gestion. Le calendrier dépend fortement de la maturité du projet et de la disponibilité des professionnels de santé, c’est généralement là que les projets prennent du retard." },
  { q: "Que contient le dossier déposé auprès de l’ARS ?", a: "Il présente le porteur, le projet de santé, l’organisation prévue, l’équipe, les locaux et les engagements de la structure. C’est le document qui engage le centre sur son fonctionnement réel, pas une simple formalité administrative. Les dossiers refusés ou retardés le sont souvent parce que le projet de santé est trop générique, mal relié au diagnostic du territoire, ou incohérent avec le modèle économique annoncé. Nous aidons les porteurs à construire ce dossier et à le rendre défendable, du diagnostic initial jusqu’aux échanges avec l’agence." },
  { q: "À quoi sert vraiment le projet de santé ?", a: "C’est la colonne vertébrale du centre : il décrit la population visée, l’offre de soins, les modalités d’accès, la coordination interne et les liens avec les autres acteurs du territoire. Il conditionne l’avis de l’ARS, mais il sert surtout d’outil de pilotage une fois le centre ouvert. Un projet de santé bien construit facilite le recrutement, structure l’organisation et rend les demandes de financement plus solides. Un projet copié sur un modèle générique se retourne rapidement contre la structure." },
  { q: "Quel statut juridique choisir pour le gestionnaire ?", a: "Un centre de santé est géré par une personne morale à but non lucratif ou publique : association, mutuelle, fondation, collectivité territoriale ou groupement, établissement de santé, société coopérative d’intérêt collectif. Chaque forme a ses conséquences en matière de gouvernance, de fiscalité, de responsabilité et de rapport aux financeurs. Le choix se raisonne à partir du porteur du projet, de ses partenaires et de la manière dont il souhaite associer les professionnels et les usagers. C’est une décision structurante qu’il vaut mieux prendre au bon moment, car la faire évoluer ensuite coûte cher en temps et en énergie." },
  { q: "Pourquoi les médecins exercent-ils sous statut salarié ?", a: "C’est le principe même du centre de santé : les professionnels y sont salariés du gestionnaire, qui assume l’organisation, la facturation et la responsabilité d’employeur. Pour le praticien, cela signifie une rémunération stable, pas de gestion de cabinet et une couverture sociale de salarié. Pour la structure, cela suppose une masse salariale à financer indépendamment des aléas d’activité, ce qui rend le pilotage du temps médical déterminant. C’est aussi ce qui rend le centre de santé attractif auprès des jeunes praticiens qui ne souhaitent pas s’installer en libéral." },
  { q: "Comment attirer et fidéliser des médecins salariés ?", a: "La rémunération compte, mais elle est rarement le facteur décisif à elle seule. Ce qui fait rester un praticien, c’est la qualité de l’organisation : secrétariat efficace, plateau technique correct, logiciel qui fonctionne, temps administratif réduit, équipe stable et gouvernance qui tient ses engagements. Le contrat doit être clair sur le temps de travail, les astreintes, la participation à la vie de la structure et les perspectives d’évolution. Nous travaillons autant sur l’attractivité réelle du poste que sur le sourcing, car recruter pour voir partir le praticien dans l’année coûte plus cher que de ne pas recruter." },
  { q: "Comment fonctionnent le conventionnement et le tiers payant ?", a: "Le centre de santé relève de l’accord national conclu entre les représentants des centres et l’Assurance Maladie, qui encadre ses relations avec les caisses et ouvre l’accès à certains financements conventionnels. Il pratique la dispense d’avance de frais pour les patients, ce qui fait de la facturation et du recouvrement un sujet de gestion à part entière. Un centre qui facture mal, qui laisse filer les rejets ou qui suit mal ses flux se fragilise en trésorerie sans que cela se voie tout de suite dans les comptes. C’est l’un des premiers points que nous regardons lors d’un audit." },
  { q: "Quels indicateurs de pilotage suivre au quotidien ?", a: "L’essentiel tient en quelques familles : l’activité par professionnel et par plage, le taux d’occupation des créneaux, les rendez-vous non honorés, la facturation effectivement encaissée, les rejets et impayés, la masse salariale rapportée aux recettes et la trésorerie disponible. L’enjeu n’est pas d’empiler les tableaux mais d’avoir un jeu réduit d’indicateurs regardés à intervalle fixe par la direction. Beaucoup de centres découvrent leurs difficultés à la clôture des comptes, donc trop tard pour réagir. Un pilotage mensuel simple change complètement la capacité de la structure à corriger le tir." },
  { q: "Notre centre est déficitaire, pouvez-vous intervenir ?", a: "Oui, c’est une part importante de notre activité. Nous commençons par établir un diagnostic honnête : structure des recettes, temps médical réellement produit, organisation de la facturation, charges fixes, financements non perçus et situation de trésorerie. La sortie de crise combine généralement plusieurs leviers, rarement un seul, et suppose des décisions que la gouvernance doit assumer. Nous accompagnons aussi les reprises de centres en difficulté, où la question est de savoir ce qui peut être sauvé et à quelles conditions. Contactez-nous pour un check-up." },
];
