export type Service = {
  slug: string;
  name: string;
  short: string;
  hero: string;
  icon: string; // SVG path
  pillars: { title: string; desc: string }[];
  metaTitle: string;
  metaDescription: string;
  keywords: string[];
};

// Icon paths (24x24)
const ICONS = {
  euro: "M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8zm-1-13h4v2h-4v2h4v2h-4c-.55 0-1 .45-1 1v1h5v2H8v-2h2v-1c0-2.21 1.79-4 4-4h-3V7z",
  building: "M12 3L2 12h3v8h6v-6h2v6h6v-8h3L12 3z",
  user: "M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z",
  chart: "M3 13h2v8H3v-8zm4-4h2v12H7V9zm4-4h2v16h-2V5zm4 8h2v8h-2v-8zm4-4h2v12h-2V9z",
  grid: "M3 3h7v7H3V3zm11 0h7v7h-7V3zM3 14h7v7H3v-7zm11 0h7v7h-7v-7z",
  megaphone: "M3 10v4l8 4V6L3 10zm12-3l3 1v8l-3 1v3l5-1V5l-5-1v3z",
  rocket: "M13 14l1.5-1.5L17 15l-1.5 1.5L13 14zM5 21l3-7 4 4-7 3zm14-9l-3-3 5-5 3 3-5 5zm-9.5-1.5L6 13l-1.5-1.5L8 8l1.5 2.5z",
  receipt: "M19 3l-1.5 1.5L16 3l-1.5 1.5L13 3l-1.5 1.5L10 3l-1.5 1.5L7 3 5.5 4.5 4 3v18l1.5-1.5L7 21l1.5-1.5L10 21l1.5-1.5L13 21l1.5-1.5L16 21l1.5-1.5L19 21V3z",
  document: "M14 2H6c-1.1 0-2 .9-2 2v16c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V8l-6-6zm-1 7V3.5L18.5 9H13z",
  truck: "M20 8h-3V4H1v13h2c0 1.66 1.34 3 3 3s3-1.34 3-3h6c0 1.66 1.34 3 3 3s3-1.34 3-3h2v-5l-3-4zM6 18.5c-.83 0-1.5-.67-1.5-1.5s.67-1.5 1.5-1.5 1.5.67 1.5 1.5-.67 1.5-1.5 1.5zM19.5 9.5l1.96 2.5H17V9.5h2.5zM18 18.5c-.83 0-1.5-.67-1.5-1.5s.67-1.5 1.5-1.5 1.5.67 1.5 1.5-.67 1.5-1.5 1.5z",
  shield: "M12 1L3 5v6c0 5.55 3.84 10.74 9 12 5.16-1.26 9-6.45 9-12V5l-9-4zm-2 16l-4-4 1.41-1.41L10 14.17l6.59-6.59L18 9l-8 8z",
  search: "M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5z",
};

export const services: Service[] = [
  {
    slug: "subventions-et-financements",
    name: "Subventions & financements",
    short: "Nous récupérons les subventions pour vous.",
    hero: "Nous récupérons les subventions pour vous. Cartographie complète des dispositifs publics et conventionnels mobilisables par votre centre, montage des dossiers, suivi auprès des organismes.",
    icon: ICONS.euro,
    pillars: [
      { title: "Cartographie complète", desc: "Tous les financements auxquels votre centre peut prétendre, identifiés et chiffrés." },
      { title: "Montage des dossiers", desc: "Préparation, dépôt, relances : on s’occupe de tout." },
      { title: "Subvention Teulade", desc: "Dispositif spécifique aux centres de santé conventionnés (article L162-32 du code de la sécurité sociale)." },
      { title: "Articulation des dispositifs", desc: "Articulation ACI, FIR, aides régionales, aides à l’installation pour maximiser sans doublon." },
    ],
    metaTitle: "Subventions et financements pour centres de santé",
    metaDescription: "Nous récupérons les subventions pour vous. Mobilisation des dispositifs ACI, FIR, subvention Teulade, aides à l’installation, fonds collectivités.",
    keywords: ["subventions centre de santé", "financements centre de santé", "subvention Teulade", "ACI", "FIR"],
  },
  {
    slug: "creation-centre-de-sante",
    name: "Création de centre de santé",
    short: "On crée votre centre, de l’idée à l’ouverture.",
    hero: "De l’étude de faisabilité jusqu’à l’ouverture des portes : étude territoriale, statut juridique, projet de santé, dossier ARS, plan de financement.",
    icon: ICONS.building,
    pillars: [
      { title: "Étude de faisabilité", desc: "Diagnostic territorial, zonage ARS, modélisation économique." },
      { title: "Constitution juridique", desc: "Choix du statut (association, SCIC, SCM, mutualiste, public), formalités." },
      { title: "Projet de santé", desc: "Rédaction du document exigé par l’ARS." },
      { title: "Dossier ARS", desc: "Constitution du dossier d’ouverture, échanges avec l’agence." },
      { title: "Plan de financement", desc: "Recettes prévisionnelles, aides à l’installation, cofinancements." },
    ],
    metaTitle: "Créer un centre de santé : accompagnement complet",
    metaDescription: "Création d’un centre de santé : étude de faisabilité, statut juridique, projet de santé, dossier ARS, plan de financement.",
    keywords: ["créer un centre de santé", "ouvrir un centre de santé", "projet de santé", "dossier ARS"],
  },
  {
    slug: "recrutement-de-medecins",
    name: "Recrutement de médecins",
    short: "Vos médecins, on s’en occupe.",
    hero: "Sourcer, attirer, recruter et fidéliser vos médecins. Approche directe, ingénierie contractuelle, attractivité salariale.",
    icon: ICONS.user,
    pillars: [
      { title: "Sourcing actif", desc: "Approche directe de médecins ciblés sur le territoire." },
      { title: "Marque employeur", desc: "Positionnement du centre, supports d’attractivité." },
      { title: "Contrats & rémunération", desc: "Statut salarié, package, clauses spécifiques." },
      { title: "Intégration & fidélisation", desc: "Onboarding, parcours, animation de l’équipe médicale." },
    ],
    metaTitle: "Recrutement de médecins pour centres de santé",
    metaDescription: "Vos médecins, on s’en occupe. Sourcing, attractivité, contrats, intégration et fidélisation.",
    keywords: ["recrutement médecin centre de santé", "recruter un médecin salarié", "médecin salarié"],
  },
  {
    slug: "optimisation-de-l-activite",
    name: "Optimisation de l’activité",
    short: "Plus de patients, mieux soignés, mieux facturés.",
    hero: "On augmente votre activité et vos recettes : pilotage du taux d’occupation, cotation, facturation, indicateurs ACI, satisfaction patient.",
    icon: ICONS.chart,
    pillars: [
      { title: "Pilotage de l’occupation", desc: "Analyse du planning, équilibrage, plages sous-utilisées." },
      { title: "Cotation & facturation", desc: "Revue CCAM/NGAP, conformité, optimisation." },
      { title: "Indicateurs ACI & ROSP", desc: "Pilotage des indicateurs forfaitaires et satisfaction." },
      { title: "Reporting", desc: "Tableaux de bord clairs pour la direction." },
    ],
    metaTitle: "Optimisation de l’activité d’un centre de santé",
    metaDescription: "Optimisation de l’activité d’un centre de santé : occupation, cotation, facturation, indicateurs ACI et ROSP.",
    keywords: ["optimisation activité centre de santé", "cotation centre de santé", "indicateurs ACI"],
  },
  {
    slug: "conseil-en-organisation",
    name: "Conseil en organisation",
    short: "Une équipe qui tourne, un centre qui scale.",
    hero: "Process internes, gouvernance, flux patients, planification, coordination des équipes. On structure ce qui doit tourner sans vous.",
    icon: ICONS.grid,
    pillars: [
      { title: "Audit organisationnel", desc: "Cartographie des process, points de friction." },
      { title: "Refonte des flux", desc: "Parcours patient, RDV, accueil, facturation." },
      { title: "Gouvernance", desc: "Comité de direction, instances médicales, IRP." },
      { title: "Outils & logiciels", desc: "Choix et déploiement des logiciels métiers." },
    ],
    metaTitle: "Conseil en organisation pour centres de santé",
    metaDescription: "Conseil en organisation : process, gouvernance, flux patients, planning, outils métiers.",
    keywords: ["conseil organisation centre de santé", "process centre de santé"],
  },
  {
    slug: "patientele-et-communication",
    name: "Patientèle & communication",
    short: "Plus de patients, plus de fidélité.",
    hero: "Référencement local, Google, Doctolib, communication territoriale, fidélisation. On amène des patients et on les fait rester.",
    icon: ICONS.megaphone,
    pillars: [
      { title: "Référencement local (SEO)", desc: "Google Maps, fiches d’établissement, présence locale." },
      { title: "Prise de RDV en ligne", desc: "Doctolib, Maiia, Keldoc — paramétrage et optimisation." },
      { title: "Communication territoriale", desc: "Mairie, médico-social, prescripteurs locaux." },
      { title: "Rétention patient", desc: "Rappels, satisfaction, parcours fluide." },
    ],
    metaTitle: "Patientèle & communication pour centres de santé",
    metaDescription: "Référencement local, Doctolib, communication territoriale, fidélisation patient.",
    keywords: ["communication centre de santé", "Doctolib centre de santé", "patientèle"],
  },
  {
    slug: "developpement",
    name: "Développement & antennes",
    short: "Du premier centre au réseau.",
    hero: "Faire grandir un centre déjà en activité : élargissement de l’offre, ouverture d’antennes, structuration multi-sites, montée en charge financière.",
    icon: ICONS.rocket,
    pillars: [
      { title: "Diagnostic stratégique", desc: "Patientèle, recettes, marges de progression." },
      { title: "Élargissement de l’offre", desc: "Spécialités, paramédical, télémédecine." },
      { title: "Ouverture d’antennes", desc: "Étude d’opportunité, multi-sites, mutualisation." },
      { title: "Montée en charge", desc: "Articulation des financements existants et nouveaux." },
    ],
    metaTitle: "Développer un centre de santé : antennes, offre, RH",
    metaDescription: "Du premier centre au réseau : élargissement de l’offre, ouverture d’antennes, RH, financements.",
    keywords: ["développer un centre de santé", "ouvrir une antenne"],
  },
  {
    slug: "comptabilite-gestion",
    name: "Comptabilité & gestion",
    short: "On pilote vos chiffres, vous pilotez vos soins.",
    hero: "Tenue de gestion, suivi budgétaire, paie, fiscalité pensés pour le secteur. Vos chiffres structurés, vos tableaux de bord clairs, des alertes au bon moment.",
    icon: ICONS.receipt,
    pillars: [
      { title: "Tenue de gestion", desc: "Comptabilité analytique adaptée, ventilation par activité." },
      { title: "Pilotage budgétaire", desc: "Budget, alertes, prévisions de trésorerie." },
      { title: "Paie & social", desc: "Bulletins, DSN, attestations, conformité." },
      { title: "Fiscalité", desc: "Optimisation selon le statut (association, mutuelle, SCIC, public)." },
      { title: "Reporting", desc: "Tableaux de bord direction et administrateurs." },
    ],
    metaTitle: "Comptabilité et gestion d’un centre de santé",
    metaDescription: "Tenue de gestion, pilotage budgétaire, paie, fiscalité pensés pour les centres de santé.",
    keywords: ["comptabilité centre de santé", "gestion centre de santé"],
  },
  {
    slug: "dossier-ars",
    name: "Dossier ARS",
    short: "On monte vos dossiers, vous obtenez les fonds.",
    hero: "Élaboration, dépôt et suivi de vos dossiers ARS : ouvertures, renouvellements, financements, mise en conformité.",
    icon: ICONS.document,
    pillars: [
      { title: "Diagnostic des attendus", desc: "Lecture des appels à projets, critères d’évaluation." },
      { title: "Rédaction du dossier", desc: "Projet, indicateurs, budget, gouvernance." },
      { title: "Annexes financières", desc: "Plan de financement, articulation FIR, ACI, collectivités." },
      { title: "Dépôt & relances", desc: "Suivi jusqu’à la décision." },
      { title: "Reporting post-octroi", desc: "Bilans intermédiaires et finaux." },
    ],
    metaTitle: "Monter un dossier ARS pour un centre de santé",
    metaDescription: "Montage de dossier ARS clé en main : rédaction, annexes financières, dépôt, suivi.",
    keywords: ["dossier ARS centre de santé", "appel à projets ARS", "FIR"],
  },
  {
    slug: "achats-et-investissements",
    name: "Achats & investissements",
    short: "Le bon matériel au bon prix.",
    hero: "Négociation fournisseurs, sélection des équipements, financement des investissements : matériel médical, dentaire, informatique, immobilier.",
    icon: ICONS.truck,
    pillars: [
      { title: "Cahiers des charges", desc: "Définir le bon besoin avant d’acheter." },
      { title: "Sourcing fournisseurs", desc: "Consultation et comparaison sur le bon panel." },
      { title: "Négociation", desc: "Prix, conditions, SAV, formation incluse." },
      { title: "Financement", desc: "Crédit-bail, location longue durée, prêts adaptés." },
    ],
    metaTitle: "Achats & investissements pour centres de santé",
    metaDescription: "Achats, négociation fournisseurs, financement du matériel pour centres de santé.",
    keywords: ["achats centre de santé", "matériel centre de santé"],
  },
  {
    slug: "audit-financier",
    name: "Audit financier",
    short: "On chiffre où vous perdez de l’argent.",
    hero: "Audit financier confidentiel : recettes, charges, financements actuels, potentiel non mobilisé. Vous repartez avec un plan d’action clair et chiffré.",
    icon: ICONS.search,
    pillars: [
      { title: "Analyse des recettes", desc: "Actes, tiers payant, forfaits, ROSP, financements conventionnels." },
      { title: "Analyse des charges", desc: "Structure, rémunérations, charges sociales, immobilier." },
      { title: "Détection des angles morts", desc: "Dispositifs non mobilisés ou sous-optimisés." },
      { title: "Plan d’action chiffré", desc: "Priorisation, calendrier, potentiel récupérable." },
    ],
    metaTitle: "Audit financier d’un centre de santé",
    metaDescription: "Audit financier confidentiel : recettes, charges, financements, potentiel non mobilisé.",
    keywords: ["audit financier centre de santé"],
  },
  {
    slug: "conformite-projet-de-sante",
    name: "Conformité & projet de santé",
    short: "Vous restez en règle, on s’occupe du reste.",
    hero: "Mise à jour du projet de santé, accompagnement aux visites ARS, préparation aux contrôles, conformité réglementaire et RGPD.",
    icon: ICONS.shield,
    pillars: [
      { title: "Audit conformité", desc: "Revue documentaire et organisationnelle." },
      { title: "Projet de santé", desc: "Rédaction et mise à jour selon les attendus ARS." },
      { title: "Préparation aux visites", desc: "Coaching, dossier de visite, simulation." },
      { title: "RGPD & règlement intérieur", desc: "Politiques internes attendues." },
    ],
    metaTitle: "Conformité et projet de santé d’un centre de santé",
    metaDescription: "Mise en conformité, renouvellement du projet de santé, préparation à la visite ARS, RGPD.",
    keywords: ["projet de santé", "visite ARS", "conformité centre de santé"],
  },
];
