export type Service = {
  slug: string;
  name: string;
  short: string;
  hero: string;
  pillars: { title: string; desc: string }[];
  metaTitle: string;
  metaDescription: string;
  keywords: string[];
};

export const services: Service[] = [
  {
    slug: "subventions-et-financements",
    name: "Subventions & financements",
    short: "Nous récupérons les subventions pour vous.",
    hero: "Nous récupérons les subventions pour vous. Cartographie complète des dispositifs publics et conventionnels mobilisables par votre centre, montage des dossiers, suivi auprès des organismes.",
    pillars: [
      { title: "Cartographie complète", desc: "Tous les financements auxquels votre centre peut prétendre, identifiés et chiffrés." },
      { title: "Montage des dossiers", desc: "Préparation, dépôt, relances : on s’occupe de tout." },
      { title: "Subvention Teulade", desc: "Dispositif spécifique aux centres de santé conventionnés (article L162-32 du code de la sécurité sociale)." },
      { title: "Articulation des dispositifs", desc: "Articulation ACI, FIR, aides régionales, aides à l’installation pour maximiser sans doublon." },
    ],
    metaTitle: "Subventions et financements pour centres de santé",
    metaDescription: "Nous récupérons les subventions pour vous. Mobilisation des dispositifs ACI, FIR, subvention Teulade, aides à l’installation, fonds collectivités.",
    keywords: ["subventions centre de santé", "financements centre de santé", "subvention Teulade", "ACI", "FIR"],
  },
  {
    slug: "creation-centre-de-sante",
    name: "Création de centre de santé",
    short: "On crée votre centre, de l’idée à l’ouverture.",
    hero: "De l’étude de faisabilité jusqu’à l’ouverture des portes : étude territoriale, statut juridique, projet de santé, dossier ARS, plan de financement. On porte le projet avec vous.",
    pillars: [
      { title: "Étude de faisabilité", desc: "Diagnostic territorial, zonage ARS, modélisation économique." },
      { title: "Constitution juridique", desc: "Choix du statut (association, SCIC, SCM, mutualiste, public), formalités." },
      { title: "Projet de santé", desc: "Rédaction du document exigé par l’ARS : organisation, gouvernance, protocoles." },
      { title: "Dossier ARS", desc: "Constitution du dossier d’ouverture, échanges avec l’agence." },
      { title: "Plan de financement", desc: "Recettes prévisionnelles, aides à l’installation, cofinancements." },
    ],
    metaTitle: "Créer un centre de santé : accompagnement complet",
    metaDescription: "Création d’un centre de santé : étude de faisabilité, statut juridique, projet de santé, dossier ARS, plan de financement.",
    keywords: ["créer un centre de santé", "ouvrir un centre de santé", "projet de santé", "dossier ARS"],
  },
  {
    slug: "recrutement-de-medecins",
    name: "Recrutement de médecins",
    short: "Vos médecins, on s’en occupe.",
    hero: "Sourcer, attirer, recruter et fidéliser vos médecins. Approche directe des praticiens en exercice ou en fin d’études, ingénierie contractuelle, attractivité salariale.",
    pillars: [
      { title: "Sourcing actif", desc: "Approche directe de médecins ciblés sur le territoire." },
      { title: "Marque employeur", desc: "Positionnement du centre, supports d’attractivité." },
      { title: "Contrats & rémunération", desc: "Statut salarié, package, clauses spécifiques au secteur." },
      { title: "Intégration & fidélisation", desc: "Onboarding, parcours, animation de l’équipe médicale." },
    ],
    metaTitle: "Recrutement de médecins pour centres de santé",
    metaDescription: "Vos médecins, on s’en occupe. Sourcing, attractivité, contrats, intégration et fidélisation.",
    keywords: ["recrutement médecin centre de santé", "recruter un médecin salarié", "médecin salarié"],
  },
  {
    slug: "optimisation-de-l-activite",
    name: "Optimisation de l’activité",
    short: "Plus de patients, mieux soignés, mieux facturés.",
    hero: "On augmente votre activité et vos recettes : pilotage du taux d’occupation, cotation, facturation, indicateurs ACI, satisfaction patient.",
    pillars: [
      { title: "Pilotage de l’occupation", desc: "Analyse du planning, équilibrage, plages sous-utilisées." },
      { title: "Cotation & facturation", desc: "Revue CCAM/NGAP, conformité, optimisation." },
      { title: "Indicateurs ACI & ROSP", desc: "Pilotage des indicateurs forfaitaires et satisfaction patient." },
      { title: "Reporting", desc: "Tableaux de bord clairs pour la direction." },
    ],
    metaTitle: "Optimisation de l’activité d’un centre de santé",
    metaDescription: "Optimisation de l’activité d’un centre de santé : occupation, cotation, facturation, indicateurs ACI et ROSP.",
    keywords: ["optimisation activité centre de santé", "cotation centre de santé", "indicateurs ACI"],
  },
  {
    slug: "conseil-en-organisation",
    name: "Conseil en organisation",
    short: "Une équipe qui tourne, un centre qui scale.",
    hero: "Conseil en organisation : process internes, gouvernance, flux patients, planification, coordination des équipes. On structure ce qui doit tourner sans vous.",
    pillars: [
      { title: "Audit organisationnel", desc: "Cartographie des process, points de friction." },
      { title: "Refonte des flux", desc: "Parcours patient, prise de RDV, accueil, facturation." },
      { title: "Gouvernance", desc: "Comité de direction, instances médicales, IRP." },
      { title: "Outils & logiciels", desc: "Choix et déploiement des logiciels métiers." },
    ],
    metaTitle: "Conseil en organisation pour centres de santé",
    metaDescription: "Conseil en organisation : process, gouvernance, flux patients, planning, outils métiers.",
    keywords: ["conseil organisation centre de santé", "process centre de santé"],
  },
  {
    slug: "patientele-et-communication",
    name: "Patientèle & communication",
    short: "Plus de patients, plus de fidélité.",
    hero: "Stratégie de patientèle et communication : référencement local, présence Google, prise de RDV en ligne, communication territoriale, rétention.",
    pillars: [
      { title: "Référencement local (SEO)", desc: "Google Maps, fiches d’établissement, présence locale." },
      { title: "Prise de RDV en ligne", desc: "Doctolib, Maiia, Keldoc — paramétrage et optimisation." },
      { title: "Communication territoriale", desc: "Mairie, médico-social, prescripteurs locaux." },
      { title: "Rétention patient", desc: "Rappels, satisfaction, parcours patient fluide." },
    ],
    metaTitle: "Stratégie de patientèle & communication pour centres de santé",
    metaDescription: "Référencement local, Doctolib, communication territoriale, fidélisation patient pour les centres de santé.",
    keywords: ["communication centre de santé", "Doctolib centre de santé", "patientèle centre de santé"],
  },
  {
    slug: "developpement",
    name: "Développement & antennes",
    short: "Du premier centre au réseau.",
    hero: "Faire grandir un centre déjà en activité : élargissement de l’offre de soins, ouverture d’antennes, structuration multi-sites, montée en charge financière.",
    pillars: [
      { title: "Diagnostic stratégique", desc: "Patientèle, recettes, marges de progression." },
      { title: "Élargissement de l’offre", desc: "Nouvelles spécialités, paramédical, télémédecine." },
      { title: "Ouverture d’antennes", desc: "Étude d’opportunité, structuration multi-sites." },
      { title: "Montée en charge financière", desc: "Articulation des financements existants et nouveaux." },
    ],
    metaTitle: "Développer un centre de santé : antennes, offre, RH",
    metaDescription: "Du premier centre au réseau : élargissement de l’offre, ouverture d’antennes, RH, financements.",
    keywords: ["développer un centre de santé", "ouvrir une antenne", "agrandir un centre de santé"],
  },
  {
    slug: "comptabilite-gestion",
    name: "Comptabilité & gestion",
    short: "On pilote vos chiffres, vous pilotez vos soins.",
    hero: "Tenue de gestion, suivi budgétaire, paie, fiscalité — pensés pour le secteur. On structure vos chiffres, on vous fournit les bons tableaux, on alerte quand il faut.",
    pillars: [
      { title: "Tenue de gestion", desc: "Comptabilité analytique adaptée, ventilation par activité." },
      { title: "Pilotage budgétaire", desc: "Budget, alertes, prévisions de trésorerie." },
      { title: "Paie & social", desc: "Bulletins, DSN, attestations, conformité." },
      { title: "Fiscalité", desc: "Optimisation selon le statut (association, mutuelle, SCIC, public)." },
      { title: "Reporting", desc: "Tableaux de bord direction et administrateurs." },
    ],
    metaTitle: "Comptabilité et gestion d’un centre de santé",
    metaDescription: "Tenue de gestion, pilotage budgétaire, paie, fiscalité pensés pour les centres de santé.",
    keywords: ["comptabilité centre de santé", "gestion centre de santé", "paie centre de santé"],
  },
  {
    slug: "dossier-ars",
    name: "Dossier ARS",
    short: "On monte vos dossiers, vous obtenez les fonds.",
    hero: "Élaboration, dépôt et suivi de vos dossiers ARS : ouvertures, renouvellements, financements, mise en conformité. Du briefing au reporting post-octroi.",
    pillars: [
      { title: "Diagnostic des attendus", desc: "Lecture des appels à projets, critères d’évaluation." },
      { title: "Rédaction du dossier", desc: "Projet, indicateurs, budget, gouvernance." },
      { title: "Annexes financières", desc: "Plan de financement, articulation FIR, ACI, collectivités." },
      { title: "Dépôt & relances", desc: "Suivi jusqu’à la décision." },
      { title: "Reporting post-octroi", desc: "Bilans intermédiaires et finaux exigés par l’ARS." },
    ],
    metaTitle: "Monter un dossier ARS pour un centre de santé",
    metaDescription: "Montage de dossier ARS clé en main : rédaction, annexes financières, dépôt, suivi.",
    keywords: ["dossier ARS centre de santé", "appel à projets ARS", "FIR centre de santé"],
  },
  {
    slug: "achats-et-investissements",
    name: "Achats & investissements",
    short: "Le bon matériel au bon prix.",
    hero: "Négociation fournisseurs, sélection des équipements, financement des investissements : matériel médical, dentaire, informatique, immobilier.",
    pillars: [
      { title: "Cahiers des charges", desc: "Définir le bon besoin avant d’acheter." },
      { title: "Sourcing fournisseurs", desc: "Consultation et comparaison sur le bon panel." },
      { title: "Négociation", desc: "Prix, conditions, SAV, formation incluse." },
      { title: "Financement", desc: "Crédit-bail, location longue durée, prêts adaptés." },
    ],
    metaTitle: "Achats & investissements pour centres de santé",
    metaDescription: "Achats, négociation fournisseurs, financement du matériel pour les centres de santé.",
    keywords: ["achats centre de santé", "matériel centre de santé", "équipement médical"],
  },
  {
    slug: "audit-financier",
    name: "Audit financier",
    short: "On chiffre où vous perdez de l’argent.",
    hero: "Audit financier confidentiel : recettes, charges, financements actuels, potentiel non mobilisé. Vous repartez avec un plan d’action clair et chiffré.",
    pillars: [
      { title: "Analyse des recettes", desc: "Actes, tiers payant, forfaits, ROSP, financements conventionnels." },
      { title: "Analyse des charges", desc: "Structure, rémunérations, charges sociales, immobilier." },
      { title: "Détection des angles morts", desc: "Dispositifs non mobilisés ou sous-optimisés." },
      { title: "Plan d’action chiffré", desc: "Priorisation, calendrier, potentiel récupérable." },
    ],
    metaTitle: "Audit financier d’un centre de santé",
    metaDescription: "Audit financier confidentiel : recettes, charges, financements, potentiel non mobilisé.",
    keywords: ["audit financier centre de santé", "diagnostic financier centre de santé"],
  },
  {
    slug: "conformite-projet-de-sante",
    name: "Conformité & projet de santé",
    short: "Vous restez en règle, on s’occupe du reste.",
    hero: "Mise à jour du projet de santé, accompagnement aux visites ARS, préparation aux contrôles, conformité réglementaire et RGPD.",
    pillars: [
      { title: "Audit conformité", desc: "Revue documentaire et organisationnelle." },
      { title: "Projet de santé", desc: "Rédaction et mise à jour selon les attendus ARS." },
      { title: "Préparation aux visites", desc: "Coaching, dossier de visite, simulation." },
      { title: "RGPD & règlement intérieur", desc: "Politiques internes attendues." },
    ],
    metaTitle: "Conformité et projet de santé d’un centre de santé",
    metaDescription: "Mise en conformité, renouvellement du projet de santé, préparation à la visite ARS, RGPD.",
    keywords: ["projet de santé", "visite ARS", "conformité centre de santé"],
  },
];
